//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThRejectApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RejectDbEntities : DbContext
    {
        public RejectDbEntities()
            : base("name=RejectDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbItem> tbItems { get; set; }
        public virtual DbSet<tbReturn_Reasons> tbReturn_Reasons { get; set; }
        public virtual DbSet<tbSalePurchase_Person> tbSalePurchase_Person { get; set; }
        public virtual DbSet<tbVendor> tbVendors { get; set; }
        public virtual DbSet<tbRejectRecord> tbRejectRecords { get; set; }
    }
}
