//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThRejectApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVendor
    {
        public string No { get; set; }
        public string Address { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public string Country_Region_Code { get; set; }
        public string Purchase_Code { get; set; }
        public string Search_Name { get; set; }
    }
}
